<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = '../SubDirectory.xsd' />
    <xs:include schemaLocation = '../../Name.xsd' />
    <xs:include schemaLocation = '../File.xsd' />

    <xs:include schemaLocation = './mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        substitutionGroup = 'Content-Item'
        name = 'macro'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cclassname.3E' >
                            🛈 ⁣
                        </a>

                        Macro

                    </h3>

                    <hr>

                    <p> Declares a macro. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element ref = 'subdirectory' />
                    <xs:element ref = 'name' />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'file'
                    />

                </xs:choice>
            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>