<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../SubDirectory.xsd' />
    <xs:include schemaLocation = '../../Name.xsd' />
    <xs:include schemaLocation = '../File.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'macro' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cclassname.3E)

                Macro

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element ref = 'subdirectory' />
                    <xs:element ref = 'name' />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'file'
                    />

                </xs:choice>
            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>