<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = './Branch.xsd' />
    <xs:include schemaLocation = './Type.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        name = 'url'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Curl.3E' >
                            🛈 ⁣
                        </a>

                        Url

                    </h3>

                    <hr>

                    <p> Link to a resource related to this package. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base = 'xs:anyURI' >

                    <xs:attribute
                        type = 'Url-Type'
                        name = 'type'
                        use = 'required'
                    />

                    <xs:attribute
                        type = 'Url-Branch'
                        name = 'branch'
                        use = 'optional'
                    />

                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

    </xs:element>

</xs:schema>