<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema'
>
    <xs:simpleType name = 'Python-PyCollaDA' >
        <xs:restriction base = 'xs:string' >
            <xs:enumeration value = 'collada' >
                <xs:annotation>
                    <xs:documentation>

                        <![CDATA[

                            <h3> PyCollaDA </h3>

                            <p> File IO for CollaDA files. </p>

                            <hr>

                            <p>
                                <a href = 'https://pypi.org/project/collada/' >
                                    <b> 📦 ⁣PyPI </b>
                                </a>
                            </p>

                        ]]>

                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>