<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:simpleType name = 'Python-QTPy' >
        <xs:restriction base = 'xs:string' >
            <xs:enumeration value = 'qtpy' >
                <xs:annotation>
                    <xs:documentation>

                        <![CDATA[

                            <h3> QTPy </h3>

                            <p> PyQT 5 / 6 & PySide 2 / 6 Abstraction layer. </p>

                            <hr>

                            <p>
                                <a href = 'https://pypi.org/project/qtpy/' >
                                    <b> 📦 ⁣PyPI </b>
                                </a>
                            </p>

                        ]]>

                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>