
name : '📊 𝗧𝗿𝗮𝗰𝗸 𝗮𝗱𝗼𝗽𝘁𝗶𝗼𝗻'

description : Track the schema adoption progress.

assignees : [ PhoneDroid ]
labels : []

body:

    -
        type : markdown
        attributes :
            value : |
                This issue tracks the adoption of the
                manifest schema for the linked addon.

    -
        type : checkboxes
        id : Existing-Issue

        attributes :

            description : Please check if your [Issue](https://github.com/FreeCAD/FreeCAD-Addon-Manifest-Schema/issues) has already been tracked.
            label : Existing Issue

            options:
                -   required : true
                    label : No issue exists for my addon.

    -
        type : checkboxes
        id : Code-Of-Conduct

        attributes :

            description : Please confirm that you agree to follow [Code of Conduct](https://github.com/FreeCAD/FreeCAD-Addon-Manifest-Schema?tab=coc-ov-file#readme).
            label : Code of Conduct

            options:
                -   required : true
                    label : I agree to follow the [Code of Conduct](https://github.com/FreeCAD/FreeCAD-Addon-Manifest-Schema?tab=coc-ov-file#readme).

    -
        type : input
        id : Repository-Url

        attributes :

            description : Link to the addon repository.
            placeholder : 'https://github.com/AddonCreators/TheAddon'
            label : Repository

        validations:
            required : true

    -
        type : input
        id : Pull-Request

        attributes :

            description : Link to the PR adding schema support to the addons manifest.
            placeholder : 'https://github.com/AddonCreators/TheAddon/pull/123'
            label : Pull Request

        validations:
            required : false

