<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = './Email.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType 
        name = 'Contact'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3> Contact </h3>

                    <hr>

                    <p> Public contact information of a person. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleContent>
            <xs:extension base = 'xs:string' >

                <xs:attribute
                    name = 'email'
                    type = 'Email'
                    use = 'optional'
                />

            </xs:extension>
        </xs:simpleContent>
    
    </xs:complexType>

</xs:schema>