<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:simpleType name = 'Email' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Ctag.3E' >
                            🛈 ⁣
                        </a>

                        Email

                    </h3>

                    <hr>

                    <p> Public email of the person used for inquiries. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:union>

            <!-- Example -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:enumeration value = 'User@Example.com' />
                </xs:restriction>
            </xs:simpleType>

            <!-- General -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string'>
                    <xs:pattern value = '[^@]*@[^\.]+\..+' />
                </xs:restriction>
            </xs:simpleType>

        </xs:union>
    </xs:simpleType>

</xs:schema>