<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:simpleType name = 'Manifest-Version' >

        <xs:restriction base = 'xs:integer'>
            <xs:enumeration value = '1' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Basic-Semantic-Version' >
        <xs:union>

            <!-- Example -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:enumeration value = '0.1.0' />
                    <xs:enumeration value = '5.10.1' />
                    <xs:enumeration value = '1.4.152' />
                </xs:restriction>
            </xs:simpleType>

            <!-- General -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string'>
                    <xs:pattern value = '(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)' />
                </xs:restriction>
            </xs:simpleType>

        </xs:union>
    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Semantic-Version' >

        <!--
            Abbreviated version from:
            https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        -->

        <xs:restriction base = 'xs:string'>
            <xs:pattern value = '(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Calender-Version' >

        <xs:restriction base = 'xs:token'>
            <xs:pattern value = '([1-9]{4})\.([0-9][1-9])\.([0-9][1-9])(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?' />
        </xs:restriction>

    </xs:simpleType>

</xs:schema>