<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:simpleType name = 'Addon-Name' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3> Addon </h3>

                    <hr>

                    <p> Name of a community made addon. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'xs:string' >
            <xs:pattern value = '[\s\S]+' />
        </xs:restriction>

    </xs:simpleType>

</xs:schema>