<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:simpleType name = 'Internal-Mod' >
        <xs:restriction base = 'xs:string' >

            <xs:enumeration value = 'bim' />
            <xs:enumeration value = 'assembly' />
            <xs:enumeration value = 'draft' />
            <xs:enumeration value = 'fem' />
            <xs:enumeration value = 'mesh' />
            <xs:enumeration value = 'openscad' />
            <xs:enumeration value = 'part' />
            <xs:enumeration value = 'partdesign' />
            <xs:enumeration value = 'cam' />
            <xs:enumeration value = 'plot' />
            <xs:enumeration value = 'points' />
            <xs:enumeration value = 'robot' />
            <xs:enumeration value = 'sketcher' />
            <xs:enumeration value = 'spreadsheet' />
            <xs:enumeration value = 'techdraw' />

        </xs:restriction>
    </xs:simpleType>
</xs:schema>