<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = './Python-Package.xsd' />
    <xs:include schemaLocation = './Internal-Mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Dependency-Name' >
        <xs:union>

            <!-- Community Addon -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:pattern value = '[\s\S]+' />
                </xs:restriction>
            </xs:simpleType>

            <!-- Python Package -->

            <xs:simpleType>
                <xs:restriction base = 'Python-Package' />
            </xs:simpleType>

            <!-- Internal Mod -->

            <xs:simpleType>
                <xs:restriction base = 'Internal-Mod' />
            </xs:simpleType>

        </xs:union>

    </xs:simpleType>
</xs:schema>