<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = './Internal/mod.xsd' />
    <xs:include schemaLocation = './Python/mod.xsd' />
    <xs:include schemaLocation = './Addon.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Dependency-Name' >
        <xs:union>

            <!-- Community Addon -->

            <xs:simpleType>
                <xs:restriction base = 'Addon-Name' />
            </xs:simpleType>

            <!-- Python Package -->

            <xs:simpleType>
                <xs:restriction base = 'Python-Name' />
            </xs:simpleType>

            <!-- Internal Mod -->

            <xs:simpleType>
                <xs:restriction base = 'Internal-Name' />
            </xs:simpleType>

        </xs:union>

    </xs:simpleType>
</xs:schema>