<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Contact.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        name = 'author'
        type = 'Contact'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cauthor.3E' >
                            🛈 ⁣
                        </a>

                        Author

                    </h3>

                    <hr>

                    <p> The publicly listed author(s) of the addon. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

    </xs:element>

</xs:schema>