<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = '../Helper/Contact.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType
        final = '#all'
        name = 'Package-Author'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cauthor.3E' >
                            🛈 ⁣
                        </a>

                        Author

                    </h3>

                    <hr>

                    <p> The people that contributed to this addon. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleContent>
            <xs:restriction base = 'Contact' />
        </xs:simpleContent>

    </xs:complexType>

</xs:schema>