<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = '../Helper/Dependency/mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType
        final = '#all'
        name = 'Package-Conflict'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cconflict.3E' >
                            🛈 ⁣
                        </a>

                        Conflict

                    </h3>

                    <hr>

                    <p> Declares a package that conflicts with this one. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <xs:complexContent>
            <xs:extension base = 'Required-Dependency' />
        </xs:complexContent>

    </xs:complexType>

</xs:schema>