<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = 'Content/SubDirectory.xsd' />
    <xs:include schemaLocation = 'Content/ClassName.xsd' />
    <xs:include schemaLocation = 'Content/Icon.xsd' />
    <xs:include schemaLocation = 'Content/File.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'content' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Ccontent.3E)

                Content

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:choice>

                <xs:element
                    name = 'preferencepack'
                    type = 'Content'
                />

                <xs:element
                    name = 'workbench'
                    type = 'Content'
                />

                 <xs:element
                    name = 'macro'
                    type = 'Content'
                />

            </xs:choice>
        </xs:complexType>

    </xs:element>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType name = 'Content' >
        <xs:sequence>
            <xs:choice maxOccurs = 'unbounded' >

                <xs:element ref = 'subdirectory' />
                <xs:element ref = 'content' />
                <xs:element ref = 'icon' />

                <xs:element
                    maxOccurs = 'unbounded'
                    ref = 'file'
                />

            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>