<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = 'Content/SubDirectory.xsd' />
    <xs:include schemaLocation = 'Content/ClassName.xsd' />
    <xs:include schemaLocation = 'Content/Icon.xsd' />
    <xs:include schemaLocation = 'Content/File.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'content' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cfile.3E)

                File

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'xs:anyURI' />
        </xs:simpleType>

    </xs:element>
</xs:schema>