<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:simpleType 
        final = '#all'
        name = 'Package-Date' 
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cdate.3E' >
                            🛈 ⁣
                        </a>

                        Date

                    </h3>

                    <hr>

                    <p> Date the current version was published. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'xs:token' >
            <xs:pattern value = '([1-9][0-9]{3}\.(([0-9][1-9])|([1-9][0-9]))\.(([0-9][1-9])|([1-9][0-9])))' />
            <xs:pattern value = '([1-9][0-9]{3}\-(([0-9][1-9])|([1-9][0-9]))\-(([0-9][1-9])|([1-9][0-9])))' />
        </xs:restriction>

    </xs:simpleType>
    
</xs:schema>
