<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:element name = 'date' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cdate.3E' >
                            🛈 ⁣
                        </a>

                        Date

                    </h3>

                    <hr>

                    <p> Date the current version was published. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'xs:token' >
                <xs:pattern value = '([1-9][0-9]{3}\.(([0-9][1-9])|([1-9][0-9]))\.(([0-9][1-9])|([1-9][0-9])))' />
                <xs:pattern value = '([1-9][0-9]{3}\-(([0-9][1-9])|([1-9][0-9]))\-(([0-9][1-9])|([1-9][0-9])))' />
            </xs:restriction>
        </xs:simpleType>

    </xs:element>
</xs:schema>
