<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Dependency/mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        type = 'Optional-Dependency'
        name = 'depend'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cdepend.3E' >
                            🛈 ⁣
                        </a>

                        Depend

                    </h3>

                    <hr>

                    <p> Declares a dependency on an internal mode, a community addon or an allowed Python package. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

    </xs:element>

</xs:schema>