<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:simpleType
        final = '#all'
        name = 'Package-Description'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cdescription.3E' >
                            🛈 ⁣
                        </a>

                        Description

                    </h3>

                    <hr>

                    <p> Short summary of the functionality of your addon. </p>

                    <p> ⁣ </p>

                    <h4> 💡 ⁣ Example </h4>

                    <code> Animate objects with a node editor. </code>

                    <p> ⁣ </p>

                    <h4> ⚠ ⁣ Reminder </h4>

                    <p> Try to be concise and context aware. </p>

                    <p> There is no need to use phrases like: </p>

                    <ul>
                        <li> <code> This addon does .. </code> </li>
                        <li> <code> This workbench allows you to .. </code> </li>
                    </ul>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'xs:string' >
            <xs:maxLength value = '200' />
            <xs:minLength value = '10' />
        </xs:restriction>

    </xs:simpleType>

</xs:schema>