<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema'
>

    <xs:simpleType
        final = '#all'
        name = 'Package-Format'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#Attributes' >
                            🛈 ⁣
                        </a>

                        Format

                    </h3>

                    <hr>

                    <p> Version of the format used in this manifest. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'xs:integer'>
            <xs:enumeration value = '2' />
        </xs:restriction>

    </xs:simpleType>

</xs:schema>