<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Types.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'freecadmax' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cfreecadmax.3E' >
                            🛈 ⁣
                        </a>

                        FreeCAD Maximum

                    </h3>

                    <hr>

                    <p>
                        The latest
                        <a href = 'https://github.com/FreeCAD/FreeCAD/releases' >
                            Release of FreeCAD
                        </a>
                        this addon works with.
                    </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'Basic-Semantic-Version' />
        </xs:simpleType>

    </xs:element>

</xs:schema>