<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = '../Helper/License/mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType
        final = '#all' 
        name = 'Package-License' 
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Clicense.3E' >
                            🛈 ⁣
                        </a>

                        License

                    </h3>

                    <hr>

                    <p> License(s) the content of your addon is published under. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleContent>
            <xs:extension base = 'License' >

                <xs:attribute
                    name = 'file'
                    type = 'xs:string'
                    use = 'optional'
                />

            </xs:extension>
        </xs:simpleContent>

    </xs:complexType>

</xs:schema>
