<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Types.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'maintainer' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cmaintainer.3E)

                Maintainer

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base = 'xs:string' >

                    <xs:attribute
                        name = 'email'
                        type = 'Email'
                        use = 'optional'
                    />

                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

    </xs:element>

</xs:schema>