<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema'
>

    <xs:include schemaLocation = '../Helper/Version/Manifest.xsd' />
    <xs:include schemaLocation = './FreeCAD-Minimum.xsd' />
    <xs:include schemaLocation = './FreeCAD-Maximum.xsd' />
    <xs:include schemaLocation = './Python-Minimum.xsd' />
    <xs:include schemaLocation = './Content/Icon.xsd' />
    <xs:include schemaLocation = './Description.xsd' />
    <xs:include schemaLocation = './Content/mod.xsd' />
    <xs:include schemaLocation = './Maintainer.xsd' />
    <xs:include schemaLocation = './Conflict.xsd' />
    <xs:include schemaLocation = './License.xsd' />
    <xs:include schemaLocation = './Version.xsd' />
    <xs:include schemaLocation = './Replace.xsd' />
    <xs:include schemaLocation = './Url/mod.xsd' />
    <xs:include schemaLocation = './Depend.xsd' />
    <xs:include schemaLocation = './Author.xsd' />
    <xs:include schemaLocation = './Name.xsd' />
    <xs:include schemaLocation = './Date.xsd' />
    <xs:include schemaLocation = './Tag.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        final = '#all'
        name = 'package'
    >

        <xs:annotation>
            <xs:documentation xml:lang = 'en' >

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cpackage.3E' >
                            🛈 ⁣
                        </a>

                        Package

                    </h3>

                    <hr>

                    <p> Declares an addon. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>

            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'description'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'content'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '1'
                        ref = 'license'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'version'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'date'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'name'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'icon'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '1'
                        ref = 'maintainer'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '1'
                        ref = 'author'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '0'
                        ref = 'url'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '0'
                        ref = 'depend'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '0'
                        ref = 'conflict'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '0'
                        ref = 'replace'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        minOccurs = '3'
                        ref = 'tag'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'freecadmin'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '0'
                        ref = 'freecadmax'
                    />

                    <xs:element
                        maxOccurs = '1'
                        minOccurs = '1'
                        ref = 'pythonmin'
                    />

                </xs:choice>
            </xs:sequence>

            <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

            <xs:attribute
                type = 'Version-Manifest'
                name = 'format'
                use = 'required'
            />

        </xs:complexType>

    </xs:element>

</xs:schema>