<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = './FreeCAD-Minimum.xsd' />
    <xs:include schemaLocation = './FreeCAD-Maximum.xsd' />
    <xs:include schemaLocation = './Python-Minimum.xsd' />
    <xs:include schemaLocation = './Content/Icon.xsd' />
    <xs:include schemaLocation = './Description.xsd' />
    <xs:include schemaLocation = './Content/mod.xsd' />
    <xs:include schemaLocation = './Maintainer.xsd' />
    <xs:include schemaLocation = './Conflict.xsd' />
    <xs:include schemaLocation = './License.xsd' />
    <xs:include schemaLocation = './Version.xsd' />
    <xs:include schemaLocation = './Replace.xsd' />
    <xs:include schemaLocation = './Url/mod.xsd' />
    <xs:include schemaLocation = './Depend.xsd' />
    <xs:include schemaLocation = './Author.xsd' />
    <xs:include schemaLocation = './Name.xsd' />
    <xs:include schemaLocation = './Date.xsd' />
    <xs:include schemaLocation = './Tag.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'package' >

        <xs:annotation>
            <xs:documentation xml:lang = 'en' >

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cpackage.3E' >
                            🛈 ⁣
                        </a>

                        Package

                    </h3>

                    <hr>

                    <p> Declares an addon. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>

            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element ref = 'description' />
                    <xs:element ref = 'content' />
                    <xs:element ref = 'license' />
                    <xs:element ref = 'version' />
                    <xs:element ref = 'date' />
                    <xs:element ref = 'name' />
                    <xs:element ref = 'icon' />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'maintainer'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'author'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'url'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'depend'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'conflict'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'replace'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'tag'
                    />

                    <xs:element ref = 'freecadmin' />
                    <xs:element ref = 'freecadmax' />
                    <xs:element ref = 'pythonmin' />

                </xs:choice>
            </xs:sequence>

            <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

            <xs:attribute
                type = 'Manifest-Version'
                name = 'format'
                use = 'required'
            >

                <xs:annotation>
                    <xs:documentation>

                        [🛈](https://wiki.freecad.org/Package_Metadata#Attributes)

                        Version of the format used in this manifest.

                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>

        </xs:complexType>

    </xs:element>

</xs:schema>