<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:element name = 'name' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cname.3E' >
                            🛈 ⁣
                        </a>

                        Name

                    </h3>

                    <hr>

                    <p> Name displayed in the addon manager. </p>

                    <p> Should be a simple, unique & descriptive name. </p>

                    <p> Examples : `Ribbon UI` , `Sprocket Gears` , `Pie Menu` </p>

                    <p> Refrain from using superfluous terms like `FreeCAD` in the name. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'xs:string' >
                <xs:pattern value = '[^\\/\\\\?\\%\\*\\:\\|\\"&lt;&gt;]+' />
            </xs:restriction>
        </xs:simpleType>

    </xs:element>
</xs:schema>