<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Types.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'pythonmin' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cpythonmin.3E' >
                            🛈 ⁣
                        </a>

                        Python Minimum

                    </h3>

                    <hr>

                    <p>
                        The earliest version of
                        <a href = 'https://devguide.python.org/versions/' >
                            Python
                        </a>
                        that is required to use this package.
                    </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'Basic-Semantic-Version' />
        </xs:simpleType>

    </xs:element>

</xs:schema>