<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:simpleType name = 'SPDX-License' >
        <xs:restriction base = 'xs:string' >

            <xs:enumeration value = '0BSD' />
            <xs:enumeration value = '3D-Slicer-1.0' />
            <xs:enumeration value = 'AAL' />
            <xs:enumeration value = 'Abstyles' />
            <xs:enumeration value = 'AdaCore-doc' />
            <xs:enumeration value = 'Adobe-2006' />
            <xs:enumeration value = 'Adobe-Display-PostScript' />
            <xs:enumeration value = 'Adobe-Glyph' />
            <xs:enumeration value = 'Adobe-Utopia' />
            <xs:enumeration value = 'ADSL' />
            <xs:enumeration value = 'AFL-1.1' />
            <xs:enumeration value = 'AFL-1.2' />
            <xs:enumeration value = 'AFL-2.0' />
            <xs:enumeration value = 'AFL-2.1' />
            <xs:enumeration value = 'AFL-3.0' />
            <xs:enumeration value = 'Afmparse' />
            <xs:enumeration value = 'AGPL-1.0-only' />
            <xs:enumeration value = 'AGPL-1.0-or-later' />
            <xs:enumeration value = 'AGPL-3.0-only' />
            <xs:enumeration value = 'AGPL-3.0-or-later' />
            <xs:enumeration value = 'Aladdin' />
            <xs:enumeration value = 'AMD-newlib' />
            <xs:enumeration value = 'AMDPLPA' />
            <xs:enumeration value = 'AML' />
            <xs:enumeration value = 'AML-glslang' />
            <xs:enumeration value = 'AMPAS' />
            <xs:enumeration value = 'ANTLR-PD' />
            <xs:enumeration value = 'ANTLR-PD-fallback' />
            <xs:enumeration value = 'any-OSI' />
            <xs:enumeration value = 'any-OSI-perl-modules' />
            <xs:enumeration value = 'Apache-1.0' />
            <xs:enumeration value = 'Apache-1.1' />
            <xs:enumeration value = 'Apache-2.0' />
            <xs:enumeration value = 'APAFML' />
            <xs:enumeration value = 'APL-1.0' />
            <xs:enumeration value = 'App-s2p' />
            <xs:enumeration value = 'APSL-1.0' />
            <xs:enumeration value = 'APSL-1.1' />
            <xs:enumeration value = 'APSL-1.2' />
            <xs:enumeration value = 'APSL-2.0' />
            <xs:enumeration value = 'Arphic-1999' />
            <xs:enumeration value = 'Artistic-1.0' />
            <xs:enumeration value = 'Artistic-1.0-cl8' />
            <xs:enumeration value = 'Artistic-1.0-Perl' />
            <xs:enumeration value = 'Artistic-2.0' />
            <xs:enumeration value = 'ASWF-Digital-Assets-1.0' />
            <xs:enumeration value = 'ASWF-Digital-Assets-1.1' />
            <xs:enumeration value = 'Baekmuk' />
            <xs:enumeration value = 'Bahyph' />
            <xs:enumeration value = 'Barr' />
            <xs:enumeration value = 'bcrypt-Solar-Designer' />
            <xs:enumeration value = 'Beerware' />
            <xs:enumeration value = 'Bitstream-Charter' />
            <xs:enumeration value = 'Bitstream-Vera' />
            <xs:enumeration value = 'BitTorrent-1.0' />
            <xs:enumeration value = 'BitTorrent-1.1' />
            <xs:enumeration value = 'blessing' />
            <xs:enumeration value = 'BlueOak-1.0.0' />
            <xs:enumeration value = 'Boehm-GC' />
            <xs:enumeration value = 'Boehm-GC-without-fee' />
            <xs:enumeration value = 'Borceux' />
            <xs:enumeration value = 'Brian-Gladman-2-Clause' />
            <xs:enumeration value = 'Brian-Gladman-3-Clause' />
            <xs:enumeration value = 'BSD-1-Clause' />
            <xs:enumeration value = 'BSD-2-Clause' />
            <xs:enumeration value = 'BSD-2-Clause-Darwin' />
            <xs:enumeration value = 'BSD-2-Clause-first-lines' />
            <xs:enumeration value = 'BSD-2-Clause-Patent' />
            <xs:enumeration value = 'BSD-2-Clause-Views' />
            <xs:enumeration value = 'BSD-3-Clause' />
            <xs:enumeration value = 'BSD-3-Clause-acpica' />
            <xs:enumeration value = 'BSD-3-Clause-Attribution' />
            <xs:enumeration value = 'BSD-3-Clause-Clear' />
            <xs:enumeration value = 'BSD-3-Clause-flex' />
            <xs:enumeration value = 'BSD-3-Clause-HP' />
            <xs:enumeration value = 'BSD-3-Clause-LBNL' />
            <xs:enumeration value = 'BSD-3-Clause-Modification' />
            <xs:enumeration value = 'BSD-3-Clause-No-Military-License' />
            <xs:enumeration value = 'BSD-3-Clause-No-Nuclear-License' />
            <xs:enumeration value = 'BSD-3-Clause-No-Nuclear-License-2014' />
            <xs:enumeration value = 'BSD-3-Clause-No-Nuclear-Warranty' />
            <xs:enumeration value = 'BSD-3-Clause-Open-MPI' />
            <xs:enumeration value = 'BSD-3-Clause-Sun' />
            <xs:enumeration value = 'BSD-4-Clause' />
            <xs:enumeration value = 'BSD-4-Clause-Shortened' />
            <xs:enumeration value = 'BSD-4-Clause-UC' />
            <xs:enumeration value = 'BSD-4.3RENO' />
            <xs:enumeration value = 'BSD-4.3TAHOE' />
            <xs:enumeration value = 'BSD-Advertising-Acknowledgement' />
            <xs:enumeration value = 'BSD-Attribution-HPND-disclaimer' />
            <xs:enumeration value = 'BSD-Inferno-Nettverk' />
            <xs:enumeration value = 'BSD-Protection' />
            <xs:enumeration value = 'BSD-Source-beginning-file' />
            <xs:enumeration value = 'BSD-Source-Code' />
            <xs:enumeration value = 'BSD-Systemics' />
            <xs:enumeration value = 'BSD-Systemics-W3Works' />
            <xs:enumeration value = 'BSL-1.0' />
            <xs:enumeration value = 'BUSL-1.1' />
            <xs:enumeration value = 'bzip2-1.0.6' />
            <xs:enumeration value = 'C-UDA-1.0' />
            <xs:enumeration value = 'CAL-1.0' />
            <xs:enumeration value = 'CAL-1.0-Combined-Work-Exception' />
            <xs:enumeration value = 'Caldera' />
            <xs:enumeration value = 'Caldera-no-preamble' />
            <xs:enumeration value = 'Catharon' />
            <xs:enumeration value = 'CATOSL-1.1' />
            <xs:enumeration value = 'CC-BY-1.0' />
            <xs:enumeration value = 'CC-BY-2.0' />
            <xs:enumeration value = 'CC-BY-2.5' />
            <xs:enumeration value = 'CC-BY-2.5-AU' />
            <xs:enumeration value = 'CC-BY-3.0' />
            <xs:enumeration value = 'CC-BY-3.0-AT' />
            <xs:enumeration value = 'CC-BY-3.0-AU' />
            <xs:enumeration value = 'CC-BY-3.0-DE' />
            <xs:enumeration value = 'CC-BY-3.0-IGO' />
            <xs:enumeration value = 'CC-BY-3.0-NL' />
            <xs:enumeration value = 'CC-BY-3.0-US' />
            <xs:enumeration value = 'CC-BY-4.0' />
            <xs:enumeration value = 'CC-BY-NC-1.0' />
            <xs:enumeration value = 'CC-BY-NC-2.0' />
            <xs:enumeration value = 'CC-BY-NC-2.5' />
            <xs:enumeration value = 'CC-BY-NC-3.0' />
            <xs:enumeration value = 'CC-BY-NC-3.0-DE' />
            <xs:enumeration value = 'CC-BY-NC-4.0' />
            <xs:enumeration value = 'CC-BY-NC-ND-1.0' />
            <xs:enumeration value = 'CC-BY-NC-ND-2.0' />
            <xs:enumeration value = 'CC-BY-NC-ND-2.5' />
            <xs:enumeration value = 'CC-BY-NC-ND-3.0' />
            <xs:enumeration value = 'CC-BY-NC-ND-3.0-DE' />
            <xs:enumeration value = 'CC-BY-NC-ND-3.0-IGO' />
            <xs:enumeration value = 'CC-BY-NC-ND-4.0' />
            <xs:enumeration value = 'CC-BY-NC-SA-1.0' />
            <xs:enumeration value = 'CC-BY-NC-SA-2.0' />
            <xs:enumeration value = 'CC-BY-NC-SA-2.0-DE' />
            <xs:enumeration value = 'CC-BY-NC-SA-2.0-FR' />
            <xs:enumeration value = 'CC-BY-NC-SA-2.0-UK' />
            <xs:enumeration value = 'CC-BY-NC-SA-2.5' />
            <xs:enumeration value = 'CC-BY-NC-SA-3.0' />
            <xs:enumeration value = 'CC-BY-NC-SA-3.0-DE' />
            <xs:enumeration value = 'CC-BY-NC-SA-3.0-IGO' />
            <xs:enumeration value = 'CC-BY-NC-SA-4.0' />
            <xs:enumeration value = 'CC-BY-ND-1.0' />
            <xs:enumeration value = 'CC-BY-ND-2.0' />
            <xs:enumeration value = 'CC-BY-ND-2.5' />
            <xs:enumeration value = 'CC-BY-ND-3.0' />
            <xs:enumeration value = 'CC-BY-ND-3.0-DE' />
            <xs:enumeration value = 'CC-BY-ND-4.0' />
            <xs:enumeration value = 'CC-BY-SA-1.0' />
            <xs:enumeration value = 'CC-BY-SA-2.0' />
            <xs:enumeration value = 'CC-BY-SA-2.0-UK' />
            <xs:enumeration value = 'CC-BY-SA-2.1-JP' />
            <xs:enumeration value = 'CC-BY-SA-2.5' />
            <xs:enumeration value = 'CC-BY-SA-3.0' />
            <xs:enumeration value = 'CC-BY-SA-3.0-AT' />
            <xs:enumeration value = 'CC-BY-SA-3.0-DE' />
            <xs:enumeration value = 'CC-BY-SA-3.0-IGO' />
            <xs:enumeration value = 'CC-BY-SA-4.0' />
            <xs:enumeration value = 'CC-PDDC' />
            <xs:enumeration value = 'CC-PDM-1.0' />
            <xs:enumeration value = 'CC-SA-1.0' />
            <xs:enumeration value = 'CC0-1.0' />
            <xs:enumeration value = 'CDDL-1.0' />
            <xs:enumeration value = 'CDDL-1.1' />
            <xs:enumeration value = 'CDL-1.0' />
            <xs:enumeration value = 'CDLA-Permissive-1.0' />
            <xs:enumeration value = 'CDLA-Permissive-2.0' />
            <xs:enumeration value = 'CDLA-Sharing-1.0' />
            <xs:enumeration value = 'CECILL-1.0' />
            <xs:enumeration value = 'CECILL-1.1' />
            <xs:enumeration value = 'CECILL-2.0' />
            <xs:enumeration value = 'CECILL-2.1' />
            <xs:enumeration value = 'CECILL-B' />
            <xs:enumeration value = 'CECILL-C' />
            <xs:enumeration value = 'CERN-OHL-1.1' />
            <xs:enumeration value = 'CERN-OHL-1.2' />
            <xs:enumeration value = 'CERN-OHL-P-2.0' />
            <xs:enumeration value = 'CERN-OHL-S-2.0' />
            <xs:enumeration value = 'CERN-OHL-W-2.0' />
            <xs:enumeration value = 'CFITSIO' />
            <xs:enumeration value = 'check-cvs' />
            <xs:enumeration value = 'checkmk' />
            <xs:enumeration value = 'ClArtistic' />
            <xs:enumeration value = 'Clips' />
            <xs:enumeration value = 'CMU-Mach' />
            <xs:enumeration value = 'CMU-Mach-nodoc' />
            <xs:enumeration value = 'CNRI-Jython' />
            <xs:enumeration value = 'CNRI-Python' />
            <xs:enumeration value = 'CNRI-Python-GPL-Compatible' />
            <xs:enumeration value = 'COIL-1.0' />
            <xs:enumeration value = 'Community-Spec-1.0' />
            <xs:enumeration value = 'Condor-1.1' />
            <xs:enumeration value = 'copyleft-next-0.3.0' />
            <xs:enumeration value = 'copyleft-next-0.3.1' />
            <xs:enumeration value = 'Cornell-Lossless-JPEG' />
            <xs:enumeration value = 'CPAL-1.0' />
            <xs:enumeration value = 'CPL-1.0' />
            <xs:enumeration value = 'CPOL-1.02' />
            <xs:enumeration value = 'Cronyx' />
            <xs:enumeration value = 'Crossword' />
            <xs:enumeration value = 'CrystalStacker' />
            <xs:enumeration value = 'CUA-OPL-1.0' />
            <xs:enumeration value = 'Cube' />
            <xs:enumeration value = 'curl' />
            <xs:enumeration value = 'cve-tou' />
            <xs:enumeration value = 'D-FSL-1.0' />
            <xs:enumeration value = 'DEC-3-Clause' />
            <xs:enumeration value = 'diffmark' />
            <xs:enumeration value = 'DL-DE-BY-2.0' />
            <xs:enumeration value = 'DL-DE-ZERO-2.0' />
            <xs:enumeration value = 'DOC' />
            <xs:enumeration value = 'DocBook-Schema' />
            <xs:enumeration value = 'DocBook-Stylesheet' />
            <xs:enumeration value = 'DocBook-XML' />
            <xs:enumeration value = 'Dotseqn' />
            <xs:enumeration value = 'DRL-1.0' />
            <xs:enumeration value = 'DRL-1.1' />
            <xs:enumeration value = 'DSDP' />
            <xs:enumeration value = 'dtoa' />
            <xs:enumeration value = 'dvipdfm' />
            <xs:enumeration value = 'ECL-1.0' />
            <xs:enumeration value = 'ECL-2.0' />
            <xs:enumeration value = 'EFL-1.0' />
            <xs:enumeration value = 'EFL-2.0' />
            <xs:enumeration value = 'eGenix' />
            <xs:enumeration value = 'Elastic-2.0' />
            <xs:enumeration value = 'Entessa' />
            <xs:enumeration value = 'EPICS' />
            <xs:enumeration value = 'EPL-1.0' />
            <xs:enumeration value = 'EPL-2.0' />
            <xs:enumeration value = 'ErlPL-1.1' />
            <xs:enumeration value = 'etalab-2.0' />
            <xs:enumeration value = 'EUDatagrid' />
            <xs:enumeration value = 'EUPL-1.0' />
            <xs:enumeration value = 'EUPL-1.1' />
            <xs:enumeration value = 'EUPL-1.2' />
            <xs:enumeration value = 'Eurosym' />
            <xs:enumeration value = 'Fair' />
            <xs:enumeration value = 'FBM' />
            <xs:enumeration value = 'FDK-AAC' />
            <xs:enumeration value = 'Ferguson-Twofish' />
            <xs:enumeration value = 'Frameworx-1.0' />
            <xs:enumeration value = 'FreeBSD-DOC' />
            <xs:enumeration value = 'FreeImage' />
            <xs:enumeration value = 'FSFAP' />
            <xs:enumeration value = 'FSFAP-no-warranty-disclaimer' />
            <xs:enumeration value = 'FSFUL' />
            <xs:enumeration value = 'FSFULLR' />
            <xs:enumeration value = 'FSFULLRWD' />
            <xs:enumeration value = 'FTL' />
            <xs:enumeration value = 'Furuseth' />
            <xs:enumeration value = 'fwlw' />
            <xs:enumeration value = 'GCR-docs' />
            <xs:enumeration value = 'GD' />
            <xs:enumeration value = 'generic-xts' />
            <xs:enumeration value = 'GFDL-1.1-invariants-only' />
            <xs:enumeration value = 'GFDL-1.1-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.1-no-invariants-only' />
            <xs:enumeration value = 'GFDL-1.1-no-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.1-only' />
            <xs:enumeration value = 'GFDL-1.1-or-later' />
            <xs:enumeration value = 'GFDL-1.2-invariants-only' />
            <xs:enumeration value = 'GFDL-1.2-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.2-no-invariants-only' />
            <xs:enumeration value = 'GFDL-1.2-no-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.2-only' />
            <xs:enumeration value = 'GFDL-1.2-or-later' />
            <xs:enumeration value = 'GFDL-1.3-invariants-only' />
            <xs:enumeration value = 'GFDL-1.3-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.3-no-invariants-only' />
            <xs:enumeration value = 'GFDL-1.3-no-invariants-or-later' />
            <xs:enumeration value = 'GFDL-1.3-only' />
            <xs:enumeration value = 'GFDL-1.3-or-later' />
            <xs:enumeration value = 'Giftware' />
            <xs:enumeration value = 'GL2PS' />
            <xs:enumeration value = 'Glide' />
            <xs:enumeration value = 'Glulxe' />
            <xs:enumeration value = 'GLWTPL' />
            <xs:enumeration value = 'gnuplot' />
            <xs:enumeration value = 'GPL-1.0-only' />
            <xs:enumeration value = 'GPL-1.0-or-later' />
            <xs:enumeration value = 'GPL-2.0-only' />
            <xs:enumeration value = 'GPL-2.0-or-later' />
            <xs:enumeration value = 'GPL-3.0-only' />
            <xs:enumeration value = 'GPL-3.0-or-later' />
            <xs:enumeration value = 'Graphics-Gems' />
            <xs:enumeration value = 'gSOAP-1.3b' />
            <xs:enumeration value = 'gtkbook' />
            <xs:enumeration value = 'Gutmann' />
            <xs:enumeration value = 'HaskellReport' />
            <xs:enumeration value = 'hdparm' />
            <xs:enumeration value = 'HIDAPI' />
            <xs:enumeration value = 'Hippocratic-2.1' />
            <xs:enumeration value = 'HP-1986' />
            <xs:enumeration value = 'HP-1989' />
            <xs:enumeration value = 'HPND' />
            <xs:enumeration value = 'HPND-DEC' />
            <xs:enumeration value = 'HPND-doc' />
            <xs:enumeration value = 'HPND-doc-sell' />
            <xs:enumeration value = 'HPND-export-US' />
            <xs:enumeration value = 'HPND-export-US-acknowledgement' />
            <xs:enumeration value = 'HPND-export-US-modify' />
            <xs:enumeration value = 'HPND-export2-US' />
            <xs:enumeration value = 'HPND-Fenneberg-Livingston' />
            <xs:enumeration value = 'HPND-INRIA-IMAG' />
            <xs:enumeration value = 'HPND-Intel' />
            <xs:enumeration value = 'HPND-Kevlin-Henney' />
            <xs:enumeration value = 'HPND-Markus-Kuhn' />
            <xs:enumeration value = 'HPND-merchantability-variant' />
            <xs:enumeration value = 'HPND-MIT-disclaimer' />
            <xs:enumeration value = 'HPND-Netrek' />
            <xs:enumeration value = 'HPND-Pbmplus' />
            <xs:enumeration value = 'HPND-sell-MIT-disclaimer-xserver' />
            <xs:enumeration value = 'HPND-sell-regexpr' />
            <xs:enumeration value = 'HPND-sell-variant' />
            <xs:enumeration value = 'HPND-sell-variant-MIT-disclaimer' />
            <xs:enumeration value = 'HPND-sell-variant-MIT-disclaimer-rev' />
            <xs:enumeration value = 'HPND-UC' />
            <xs:enumeration value = 'HPND-UC-export-US' />
            <xs:enumeration value = 'HTMLTIDY' />
            <xs:enumeration value = 'IBM-pibs' />
            <xs:enumeration value = 'ICU' />
            <xs:enumeration value = 'IEC-Code-Components-EULA' />
            <xs:enumeration value = 'IJG' />
            <xs:enumeration value = 'IJG-short' />
            <xs:enumeration value = 'ImageMagick' />
            <xs:enumeration value = 'iMatix' />
            <xs:enumeration value = 'Imlib2' />
            <xs:enumeration value = 'Info-ZIP' />
            <xs:enumeration value = 'Inner-Net-2.0' />
            <xs:enumeration value = 'InnoSetup' />
            <xs:enumeration value = 'Intel' />
            <xs:enumeration value = 'Intel-ACPI' />
            <xs:enumeration value = 'Interbase-1.0' />
            <xs:enumeration value = 'IPA' />
            <xs:enumeration value = 'IPL-1.0' />
            <xs:enumeration value = 'ISC' />
            <xs:enumeration value = 'ISC-Veillard' />
            <xs:enumeration value = 'Jam' />
            <xs:enumeration value = 'JasPer-2.0' />
            <xs:enumeration value = 'JPL-image' />
            <xs:enumeration value = 'JPNIC' />
            <xs:enumeration value = 'JSON' />
            <xs:enumeration value = 'Kastrup' />
            <xs:enumeration value = 'Kazlib' />
            <xs:enumeration value = 'Knuth-CTAN' />
            <xs:enumeration value = 'LAL-1.2' />
            <xs:enumeration value = 'LAL-1.3' />
            <xs:enumeration value = 'Latex2e' />
            <xs:enumeration value = 'Latex2e-translated-notice' />
            <xs:enumeration value = 'Leptonica' />
            <xs:enumeration value = 'LGPL-2.0-only' />
            <xs:enumeration value = 'LGPL-2.0-or-later' />
            <xs:enumeration value = 'LGPL-2.1-only' />
            <xs:enumeration value = 'LGPL-2.1-or-later' />
            <xs:enumeration value = 'LGPL-3.0-only' />
            <xs:enumeration value = 'LGPL-3.0-or-later' />
            <xs:enumeration value = 'LGPLLR' />
            <xs:enumeration value = 'Libpng' />
            <xs:enumeration value = 'libpng-2.0' />
            <xs:enumeration value = 'libselinux-1.0' />
            <xs:enumeration value = 'libtiff' />
            <xs:enumeration value = 'libutil-David-Nugent' />
            <xs:enumeration value = 'LiLiQ-P-1.1' />
            <xs:enumeration value = 'LiLiQ-R-1.1' />
            <xs:enumeration value = 'LiLiQ-Rplus-1.1' />
            <xs:enumeration value = 'Linux-man-pages-1-para' />
            <xs:enumeration value = 'Linux-man-pages-copyleft' />
            <xs:enumeration value = 'Linux-man-pages-copyleft-2-para' />
            <xs:enumeration value = 'Linux-man-pages-copyleft-var' />
            <xs:enumeration value = 'Linux-OpenIB' />
            <xs:enumeration value = 'LOOP' />
            <xs:enumeration value = 'LPD-document' />
            <xs:enumeration value = 'LPL-1.0' />
            <xs:enumeration value = 'LPL-1.02' />
            <xs:enumeration value = 'LPPL-1.0' />
            <xs:enumeration value = 'LPPL-1.1' />
            <xs:enumeration value = 'LPPL-1.2' />
            <xs:enumeration value = 'LPPL-1.3a' />
            <xs:enumeration value = 'LPPL-1.3c' />
            <xs:enumeration value = 'lsof' />
            <xs:enumeration value = 'Lucida-Bitmap-Fonts' />
            <xs:enumeration value = 'LZMA-SDK-9.11-to-9.20' />
            <xs:enumeration value = 'LZMA-SDK-9.22' />
            <xs:enumeration value = 'Mackerras-3-Clause' />
            <xs:enumeration value = 'Mackerras-3-Clause-acknowledgment' />
            <xs:enumeration value = 'magaz' />
            <xs:enumeration value = 'mailprio' />
            <xs:enumeration value = 'MakeIndex' />
            <xs:enumeration value = 'Martin-Birgmeier' />
            <xs:enumeration value = 'McPhee-slideshow' />
            <xs:enumeration value = 'metamail' />
            <xs:enumeration value = 'Minpack' />
            <xs:enumeration value = 'MIPS' />
            <xs:enumeration value = 'MirOS' />
            <xs:enumeration value = 'MIT' />
            <xs:enumeration value = 'MIT-0' />
            <xs:enumeration value = 'MIT-advertising' />
            <xs:enumeration value = 'MIT-Click' />
            <xs:enumeration value = 'MIT-CMU' />
            <xs:enumeration value = 'MIT-enna' />
            <xs:enumeration value = 'MIT-feh' />
            <xs:enumeration value = 'MIT-Festival' />
            <xs:enumeration value = 'MIT-Khronos-old' />
            <xs:enumeration value = 'MIT-Modern-Variant' />
            <xs:enumeration value = 'MIT-open-group' />
            <xs:enumeration value = 'MIT-testregex' />
            <xs:enumeration value = 'MIT-Wu' />
            <xs:enumeration value = 'MITNFA' />
            <xs:enumeration value = 'MMIXware' />
            <xs:enumeration value = 'Motosoto' />
            <xs:enumeration value = 'MPEG-SSG' />
            <xs:enumeration value = 'mpi-permissive' />
            <xs:enumeration value = 'mpich2' />
            <xs:enumeration value = 'MPL-1.0' />
            <xs:enumeration value = 'MPL-1.1' />
            <xs:enumeration value = 'MPL-2.0' />
            <xs:enumeration value = 'MPL-2.0-no-copyleft-exception' />
            <xs:enumeration value = 'mplus' />
            <xs:enumeration value = 'MS-LPL' />
            <xs:enumeration value = 'MS-PL' />
            <xs:enumeration value = 'MS-RL' />
            <xs:enumeration value = 'MTLL' />
            <xs:enumeration value = 'MulanPSL-1.0' />
            <xs:enumeration value = 'MulanPSL-2.0' />
            <xs:enumeration value = 'Multics' />
            <xs:enumeration value = 'Mup' />
            <xs:enumeration value = 'NAIST-2003' />
            <xs:enumeration value = 'NASA-1.3' />
            <xs:enumeration value = 'Naumen' />
            <xs:enumeration value = 'NBPL-1.0' />
            <xs:enumeration value = 'NCBI-PD' />
            <xs:enumeration value = 'NCGL-UK-2.0' />
            <xs:enumeration value = 'NCL' />
            <xs:enumeration value = 'NCSA' />
            <xs:enumeration value = 'NetCDF' />
            <xs:enumeration value = 'Newsletr' />
            <xs:enumeration value = 'NGPL' />
            <xs:enumeration value = 'NICTA-1.0' />
            <xs:enumeration value = 'NIST-PD' />
            <xs:enumeration value = 'NIST-PD-fallback' />
            <xs:enumeration value = 'NIST-Software' />
            <xs:enumeration value = 'NLOD-1.0' />
            <xs:enumeration value = 'NLOD-2.0' />
            <xs:enumeration value = 'NLPL' />
            <xs:enumeration value = 'Nokia' />
            <xs:enumeration value = 'NOSL' />
            <xs:enumeration value = 'Noweb' />
            <xs:enumeration value = 'NPL-1.0' />
            <xs:enumeration value = 'NPL-1.1' />
            <xs:enumeration value = 'NPOSL-3.0' />
            <xs:enumeration value = 'NRL' />
            <xs:enumeration value = 'NTP' />
            <xs:enumeration value = 'NTP-0' />
            <xs:enumeration value = 'O-UDA-1.0' />
            <xs:enumeration value = 'OAR' />
            <xs:enumeration value = 'OCCT-PL' />
            <xs:enumeration value = 'OCLC-2.0' />
            <xs:enumeration value = 'ODbL-1.0' />
            <xs:enumeration value = 'ODC-By-1.0' />
            <xs:enumeration value = 'OFFIS' />
            <xs:enumeration value = 'OFL-1.0' />
            <xs:enumeration value = 'OFL-1.0-no-RFN' />
            <xs:enumeration value = 'OFL-1.0-RFN' />
            <xs:enumeration value = 'OFL-1.1' />
            <xs:enumeration value = 'OFL-1.1-no-RFN' />
            <xs:enumeration value = 'OFL-1.1-RFN' />
            <xs:enumeration value = 'OGC-1.0' />
            <xs:enumeration value = 'OGDL-Taiwan-1.0' />
            <xs:enumeration value = 'OGL-Canada-2.0' />
            <xs:enumeration value = 'OGL-UK-1.0' />
            <xs:enumeration value = 'OGL-UK-2.0' />
            <xs:enumeration value = 'OGL-UK-3.0' />
            <xs:enumeration value = 'OGTSL' />
            <xs:enumeration value = 'OLDAP-1.1' />
            <xs:enumeration value = 'OLDAP-1.2' />
            <xs:enumeration value = 'OLDAP-1.3' />
            <xs:enumeration value = 'OLDAP-1.4' />
            <xs:enumeration value = 'OLDAP-2.0' />
            <xs:enumeration value = 'OLDAP-2.0.1' />
            <xs:enumeration value = 'OLDAP-2.1' />
            <xs:enumeration value = 'OLDAP-2.2' />
            <xs:enumeration value = 'OLDAP-2.2.1' />
            <xs:enumeration value = 'OLDAP-2.2.2' />
            <xs:enumeration value = 'OLDAP-2.3' />
            <xs:enumeration value = 'OLDAP-2.4' />
            <xs:enumeration value = 'OLDAP-2.5' />
            <xs:enumeration value = 'OLDAP-2.6' />
            <xs:enumeration value = 'OLDAP-2.7' />
            <xs:enumeration value = 'OLDAP-2.8' />
            <xs:enumeration value = 'OLFL-1.3' />
            <xs:enumeration value = 'OML' />
            <xs:enumeration value = 'OpenPBS-2.3' />
            <xs:enumeration value = 'OpenSSL' />
            <xs:enumeration value = 'OpenSSL-standalone' />
            <xs:enumeration value = 'OpenVision' />
            <xs:enumeration value = 'OPL-1.0' />
            <xs:enumeration value = 'OPL-UK-3.0' />
            <xs:enumeration value = 'OPUBL-1.0' />
            <xs:enumeration value = 'OSET-PL-2.1' />
            <xs:enumeration value = 'OSL-1.0' />
            <xs:enumeration value = 'OSL-1.1' />
            <xs:enumeration value = 'OSL-2.0' />
            <xs:enumeration value = 'OSL-2.1' />
            <xs:enumeration value = 'OSL-3.0' />
            <xs:enumeration value = 'PADL' />
            <xs:enumeration value = 'Parity-6.0.0' />
            <xs:enumeration value = 'Parity-7.0.0' />
            <xs:enumeration value = 'PDDL-1.0' />
            <xs:enumeration value = 'PHP-3.0' />
            <xs:enumeration value = 'PHP-3.01' />
            <xs:enumeration value = 'Pixar' />
            <xs:enumeration value = 'pkgconf' />
            <xs:enumeration value = 'Plexus' />
            <xs:enumeration value = 'pnmstitch' />
            <xs:enumeration value = 'PolyForm-Noncommercial-1.0.0' />
            <xs:enumeration value = 'PolyForm-Small-Business-1.0.0' />
            <xs:enumeration value = 'PostgreSQL' />
            <xs:enumeration value = 'PPL' />
            <xs:enumeration value = 'PSF-2.0' />
            <xs:enumeration value = 'psfrag' />
            <xs:enumeration value = 'psutils' />
            <xs:enumeration value = 'Python-2.0' />
            <xs:enumeration value = 'Python-2.0.1' />
            <xs:enumeration value = 'python-ldap' />
            <xs:enumeration value = 'Qhull' />
            <xs:enumeration value = 'QPL-1.0' />
            <xs:enumeration value = 'QPL-1.0-INRIA-2004' />
            <xs:enumeration value = 'radvd' />
            <xs:enumeration value = 'Rdisc' />
            <xs:enumeration value = 'RHeCos-1.1' />
            <xs:enumeration value = 'RPL-1.1' />
            <xs:enumeration value = 'RPL-1.5' />
            <xs:enumeration value = 'RPSL-1.0' />
            <xs:enumeration value = 'RSA-MD' />
            <xs:enumeration value = 'RSCPL' />
            <xs:enumeration value = 'Ruby' />
            <xs:enumeration value = 'Ruby-pty' />
            <xs:enumeration value = 'SAX-PD' />
            <xs:enumeration value = 'SAX-PD-2.0' />
            <xs:enumeration value = 'Saxpath' />
            <xs:enumeration value = 'SCEA' />
            <xs:enumeration value = 'SchemeReport' />
            <xs:enumeration value = 'Sendmail' />
            <xs:enumeration value = 'Sendmail-8.23' />
            <xs:enumeration value = 'Sendmail-Open-Source-1.1' />
            <xs:enumeration value = 'SGI-B-1.0' />
            <xs:enumeration value = 'SGI-B-1.1' />
            <xs:enumeration value = 'SGI-B-2.0' />
            <xs:enumeration value = 'SGI-OpenGL' />
            <xs:enumeration value = 'SGP4' />
            <xs:enumeration value = 'SHL-0.5' />
            <xs:enumeration value = 'SHL-0.51' />
            <xs:enumeration value = 'SimPL-2.0' />
            <xs:enumeration value = 'SISSL' />
            <xs:enumeration value = 'SISSL-1.2' />
            <xs:enumeration value = 'SL' />
            <xs:enumeration value = 'Sleepycat' />
            <xs:enumeration value = 'SMAIL-GPL' />
            <xs:enumeration value = 'SMLNJ' />
            <xs:enumeration value = 'SMPPL' />
            <xs:enumeration value = 'SNIA' />
            <xs:enumeration value = 'snprintf' />
            <xs:enumeration value = 'softSurfer' />
            <xs:enumeration value = 'Soundex' />
            <xs:enumeration value = 'Spencer-86' />
            <xs:enumeration value = 'Spencer-94' />
            <xs:enumeration value = 'Spencer-99' />
            <xs:enumeration value = 'SPL-1.0' />
            <xs:enumeration value = 'ssh-keyscan' />
            <xs:enumeration value = 'SSH-OpenSSH' />
            <xs:enumeration value = 'SSH-short' />
            <xs:enumeration value = 'SSLeay-standalone' />
            <xs:enumeration value = 'SSPL-1.0' />
            <xs:enumeration value = 'SugarCRM-1.1.3' />
            <xs:enumeration value = 'Sun-PPP' />
            <xs:enumeration value = 'Sun-PPP-2000' />
            <xs:enumeration value = 'SunPro' />
            <xs:enumeration value = 'SWL' />
            <xs:enumeration value = 'swrule' />
            <xs:enumeration value = 'Symlinks' />
            <xs:enumeration value = 'TAPR-OHL-1.0' />
            <xs:enumeration value = 'TCL' />
            <xs:enumeration value = 'TCP-wrappers' />
            <xs:enumeration value = 'TermReadKey' />
            <xs:enumeration value = 'TGPPL-1.0' />
            <xs:enumeration value = 'ThirdEye' />
            <xs:enumeration value = 'threeparttable' />
            <xs:enumeration value = 'TMate' />
            <xs:enumeration value = 'TORQUE-1.1' />
            <xs:enumeration value = 'TOSL' />
            <xs:enumeration value = 'TPDL' />
            <xs:enumeration value = 'TPL-1.0' />
            <xs:enumeration value = 'TrustedQSL' />
            <xs:enumeration value = 'TTWL' />
            <xs:enumeration value = 'TTYP0' />
            <xs:enumeration value = 'TU-Berlin-1.0' />
            <xs:enumeration value = 'TU-Berlin-2.0' />
            <xs:enumeration value = 'Ubuntu-font-1.0' />
            <xs:enumeration value = 'UCAR' />
            <xs:enumeration value = 'UCL-1.0' />
            <xs:enumeration value = 'ulem' />
            <xs:enumeration value = 'UMich-Merit' />
            <xs:enumeration value = 'Unicode-3.0' />
            <xs:enumeration value = 'Unicode-DFS-2015' />
            <xs:enumeration value = 'Unicode-DFS-2016' />
            <xs:enumeration value = 'Unicode-TOU' />
            <xs:enumeration value = 'UnixCrypt' />
            <xs:enumeration value = 'Unlicense' />
            <xs:enumeration value = 'UPL-1.0' />
            <xs:enumeration value = 'URT-RLE' />
            <xs:enumeration value = 'Vim' />
            <xs:enumeration value = 'VOSTROM' />
            <xs:enumeration value = 'VSL-1.0' />
            <xs:enumeration value = 'W3C' />
            <xs:enumeration value = 'W3C-19980720' />
            <xs:enumeration value = 'W3C-20150513' />
            <xs:enumeration value = 'w3m' />
            <xs:enumeration value = 'Watcom-1.0' />
            <xs:enumeration value = 'Widget-Workshop' />
            <xs:enumeration value = 'Wsuipa' />
            <xs:enumeration value = 'WTFPL' />
            <xs:enumeration value = 'wwl' />
            <xs:enumeration value = 'X11' />
            <xs:enumeration value = 'X11-distribute-modifications-variant' />
            <xs:enumeration value = 'X11-swapped' />
            <xs:enumeration value = 'Xdebug-1.03' />
            <xs:enumeration value = 'Xerox' />
            <xs:enumeration value = 'Xfig' />
            <xs:enumeration value = 'XFree86-1.1' />
            <xs:enumeration value = 'xinetd' />
            <xs:enumeration value = 'xkeyboard-config-Zinoviev' />
            <xs:enumeration value = 'xlock' />
            <xs:enumeration value = 'Xnet' />
            <xs:enumeration value = 'xpp' />
            <xs:enumeration value = 'XSkat' />
            <xs:enumeration value = 'xzoom' />
            <xs:enumeration value = 'YPL-1.0' />
            <xs:enumeration value = 'YPL-1.1' />
            <xs:enumeration value = 'Zed' />
            <xs:enumeration value = 'Zeeff' />
            <xs:enumeration value = 'Zend-2.0' />
            <xs:enumeration value = 'Zimbra-1.3' />
            <xs:enumeration value = 'Zimbra-1.4' />
            <xs:enumeration value = 'Zlib' />
            <xs:enumeration value = 'zlib-acknowledgement' />
            <xs:enumeration value = 'ZPL-1.1' />
            <xs:enumeration value = 'ZPL-2.0' />
            <xs:enumeration value = 'ZPL-2.1' />

        </xs:restriction>
    </xs:simpleType>
</xs:schema>