<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:element name = 'tag' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Ctag.3E' >
                            🛈 ⁣
                        </a>

                        Tag

                    </h3>

                    <hr>

                    <p> A keyword describing an aspect of this package. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:union>

                <!-- General -->

                <xs:simpleType>
                    <xs:restriction base = 'xs:string' />
                </xs:simpleType>

                <!-- Examples -->

                <xs:simpleType>
                    <xs:restriction base = 'xs:string' >

                        <xs:enumeration value = 'Dark' />
                        <xs:enumeration value = 'Light' />

                        <xs:enumeration value = 'Parametric' />
                        <xs:enumeration value = 'Scripting' />
                        <xs:enumeration value = 'OpenSCAD' />
                        <xs:enumeration value = 'Sketcher' />
                        <xs:enumeration value = 'Assembly' />
                        <xs:enumeration value = 'Curves' />
                        <xs:enumeration value = 'NURBS' />
                        <xs:enumeration value = 'Nodes' />
                        <xs:enumeration value = 'Pipe' />
                        <xs:enumeration value = 'Arch' />
                        <xs:enumeration value = 'Beam' />
                        <xs:enumeration value = 'Gear' />
                        <xs:enumeration value = 'Mesh' />
                        <xs:enumeration value = 'Step' />
                        <xs:enumeration value = 'ACIS' />
                        <xs:enumeration value = 'YAML' />
                        <xs:enumeration value = 'F3D' />
                        <xs:enumeration value = 'SAT' />
                        <xs:enumeration value = 'IPT' />
                        <xs:enumeration value = 'DXF' />
                        <xs:enumeration value = 'BOM' />
                        <xs:enumeration value = 'BIM' />
                        <xs:enumeration value = 'FEM' />
                        <xs:enumeration value = 'FEA' />
                        <xs:enumeration value = 'PCB' />

                        <xs:enumeration value = '3D Printing' />
                        <xs:enumeration value = 'Electronics' />
                        <xs:enumeration value = 'Import' />
                        <xs:enumeration value = 'Export' />
                        <xs:enumeration value = 'Cloud' />
                        <xs:enumeration value = 'GCode' />
                        <xs:enumeration value = 'Menu' />

                        <xs:enumeration value = 'BuiltIn' />

                    </xs:restriction>
                </xs:simpleType>

            </xs:union>
        </xs:simpleType>

    </xs:element>
</xs:schema>