<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Tag.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element
        type = 'Tag'
        name = 'tag'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Ctag.3E' >
                            🛈 ⁣
                        </a>

                        Tag

                    </h3>

                    <hr>

                    <p> A keyword describing an aspect of this package. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

    </xs:element>

</xs:schema>