<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Helper/Semantic-Version-Full.xsd' />
    <xs:include schemaLocation = '../Helper/Calender-Version.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'version' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cversion.3E' >
                            🛈 ⁣
                        </a>

                        Version

                    </h3>

                    <hr>

                    <p> Version of the current state of the package. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:union memberTypes = 'Semantic-Version-Full Calender-Version' />
        </xs:simpleType>

    </xs:element>

</xs:schema>