<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = '../Helper/Version/Semantic-Full.xsd' />
    <xs:include schemaLocation = '../Helper/Version/Calender.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType
        final = '#all'
        name = 'Package-Version'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cversion.3E' >
                            🛈 ⁣
                        </a>

                        Version

                    </h3>

                    <hr>

                    <p> Version of the current state of the package. </p>

                    <h4> 💡 ⁣ Examples </h4>

                    <ul>
                        <li><code>1.2.3</code></li>
                        <li><code>0.40.1</code></li>
                        <li><code>1.0.3-Alpha</code></li>
                    </ul>
                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:union memberTypes = 'Version-Semantic-Full Version-Calender' />

    </xs:simpleType>

</xs:schema>