<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:include schemaLocation = './Version-Greater-Equal.xsd' />
    <xs:include schemaLocation = './Version-Less-Equal.xsd' />
    <xs:include schemaLocation = './Version-Greater.xsd' />
    <xs:include schemaLocation = './Version-Equal.xsd' />
    <xs:include schemaLocation = './Version-Less.xsd' />
    <xs:include schemaLocation = './Optional.xsd' />
    <xs:include schemaLocation = './Type.xsd' />

    <xs:include schemaLocation = './Name/mod.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType name = 'Required-Dependency' >
        <xs:simpleContent>

            <xs:extension base = 'Dependency-Name' >

                <xs:attribute
                    type = 'Version-Less'
                    name = 'version_lt'
                    use = 'optional'
                />

                <xs:attribute
                    type = 'Version-Less-Equal'
                    name = 'version_lte'
                    use = 'optional'
                />

                <xs:attribute
                    type = 'Version-Equal'
                    name = 'version_eq'
                    use = 'optional'
                />

                <xs:attribute
                    type = 'Version-Greater'
                    name = 'version_gt'
                    use = 'optional'
                />

                <xs:attribute
                    type = 'Version-Greater-Equal'
                    name = 'version_gte'
                    use = 'optional'
                />

                <xs:attribute
                    type = 'Dependency-Type'
                    name = 'type'
                    use = 'required'
                />

            </xs:extension>

        </xs:simpleContent>
    </xs:complexType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:complexType name = 'Optional-Dependency' >
        <xs:simpleContent>

            <xs:extension base = 'Required-Dependency' >

                <xs:attribute
                    type = 'Dependency-Optional'
                    name = 'optional'
                    use = 'required'
                />

            </xs:extension>

        </xs:simpleContent>
    </xs:complexType>

</xs:schema>