<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Version/Semantic-Basic.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType
        name = 'Version-Equal'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#Attributes_6' >
                            🛈 ⁣
                        </a>

                        Equal

                    </h3>

                    <hr>

                    <p> Constrains this dependency to versions = to the specified value. </p>

                    <h4> 💡 ⁣ Example </h4>

                    <code lang = xml >
                    &lt;depend version_eq = '1.2.3' &gt;Package&lt;/depend&gt;
                    </code>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'Version-Semantic-Basic' />

    </xs:simpleType>

</xs:schema>