<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Types.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:attribute
        type = 'Basic-Semantic-Version'
        name = 'version_lte'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#Attributes_6' >
                            🛈 ⁣
                        </a>

                        Less Than Equal

                    </h3>

                    <hr>

                    <p> Constrains this dependency to versions ≤ to the specified value. </p>

                    <h4> 💡 ⁣ Example </h4>

                    <code lang = xml >
                    &lt;depend version_lte = '1.2.3' &gt;Package&lt;/depend&gt;
                    </code>

                ]]>

            </xs:documentation>
        </xs:annotation>

    </xs:attribute>

</xs:schema>