<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >
    <xs:element name = 'classname' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cclassname.3E' >
                            🛈 ⁣
                        </a>

                        Classname

                    </h3>

                    <hr>

                    <p> The name of the corresponding Python class. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'xs:token' />
        </xs:simpleType>

    </xs:element>
</xs:schema>