<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:simpleType 
        final = '#all'
        name = 'Package-Icon'
    >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Cicon.3E' >
                            🛈 ⁣
                        </a>

                        Icon

                    </h3>

                    <hr>

                    <p> Icon displayed in the addon manager. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:restriction base = 'xs:anyURI' />

    </xs:simpleType>
    
</xs:schema>