<?xml
    version = '1.0'
    encoding = 'UTF-8'
?>

<xs:schema 
    elementFormDefault = 'qualified'
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema' 
>

    <xs:element name = 'subdirectory' >

        <xs:annotation>
            <xs:documentation>

                <![CDATA[

                    <h3>

                        <a href = 'https://wiki.freecad.org/Package_Metadata#.3Csubdirectory.3E' >
                            🛈 ⁣
                        </a>

                        Sub-Directory

                    </h3>

                    <hr>

                    <p> Folder the item's content is located in. </p>

                ]]>

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:simpleType>
            <xs:restriction base = 'xs:anyURI' />
        </xs:simpleType>

    </xs:element>
    
</xs:schema>