<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = '../Description.xsd' />
    <xs:include schemaLocation = '../Name.xsd' />
    <xs:include schemaLocation = '../Url.xsd' />
    <xs:include schemaLocation = '../Tag.xsd' />

    <xs:include schemaLocation = './SubDirectory.xsd' />
    <xs:include schemaLocation = './ClassName.xsd' />
    <xs:include schemaLocation = './Icon.xsd' />
    <xs:include schemaLocation = './File.xsd' />

    <xs:element name = 'workbench' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cclassname.3E)

                Workbench

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element ref = 'subdirectory' />
                    <xs:element ref = 'description' />
                    <xs:element ref = 'classname' />
                    <xs:element ref = 'icon' />
                    <xs:element ref = 'name' />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'file'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'url'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'tag'
                    />

                </xs:choice>
            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>