<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = 'SPDX-Licenses.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'license' >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Clicense.3E)

                License(s) the content of your addon is published under.

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base = 'Version' >

                    <xs:attribute
                        name = 'file'
                        type = 'xs:string'
                        use = 'optional'
                    />

                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

    </xs:element>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Version' >
        <xs:union>

            <!-- Custom License -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:pattern value = '[\s\S]+' />
                </xs:restriction>
            </xs:simpleType>

            <!-- FreeCAD Specific -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:enumeration value = 'UNLICENSED' />
                </xs:restriction>
            </xs:simpleType>

            <!-- SPDX Licenses -->

                <xs:simpleType>
                <xs:restriction base = 'SPDX-License' />
            </xs:simpleType>

        </xs:union>

    </xs:simpleType>

</xs:schema>
