<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema'
>

    <xs:include schemaLocation = 'Types.xsd' />

    <xs:element
        name = 'package'
    >

        <xs:annotation>
            <xs:documentation>

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cpackage.3E)

                Declares an addon.

            </xs:documentation>
        </xs:annotation>

        <xs:complexType>

            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element
                        name = 'name'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cname.3E)

                                Name displayed in the addon manager.

                                <![CDATA[

                                    <p> Should be a simple, unique &amp; descriptive name. </p>

                                    <p> Examples : `Ribbon UI` , `Sprocket Gears` , `Pie Menu` </p>

                                    <p> Refrain from using superfluous terms like `FreeCAD` in the name. </p>

                                ]]>

                            </xs:documentation>
                        </xs:annotation>

                        <xs:simpleType>
                            <xs:restriction base = 'xs:string' >
                                <xs:pattern value = '[^\\/\\\\?\\%\\*\\:\\|\\"&lt;&gt;]+' />
                            </xs:restriction>
                        </xs:simpleType>

                    </xs:element>

                    <xs:element
                        name = 'version'
                        type = 'Version'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cversion.3E)

                                Version

                            </xs:documentation>
                        </xs:annotation>

                    </xs:element>

                    <xs:element
                        name = 'description'
                        type = 'xs:string'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cdescription.3E)

                                Description displayed in the addon manager.

                            </xs:documentation>
                        </xs:annotation>

                    </xs:element>

                    <xs:element
                        maxOccurs = 'unbounded'
                        name = 'maintainer'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cdescription.3E)

                                Maintainer

                            </xs:documentation>
                        </xs:annotation>

                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base = 'xs:string' >

                                    <xs:attribute
                                        name = 'email'
                                        type = 'Email'
                                        use = 'optional'
                                    />

                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>

                    </xs:element>

                    <xs:element
                        name = 'date'
                        type = 'xs:date'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cdescription.3E)

                                Date

                            </xs:documentation>
                        </xs:annotation>

                    </xs:element>

                    <xs:element
                        name = 'license'
                        type = 'License'
                    >

                        <xs:annotation>
                            <xs:documentation>

                                [🛈](https://wiki.freecad.org/Package_Metadata#.3Clicense.3E)

                                License(s) the content of your addon is published under.

                            </xs:documentation>
                        </xs:annotation>

                    </xs:element>

                </xs:choice>
            </xs:sequence>

            <xs:attribute
                type = 'Manifest-Version'
                name = 'format'
                use = 'required'
            >

                <xs:annotation>
                    <xs:documentation>

                        [🛈](https://wiki.freecad.org/Package_Metadata#Attributes)

                        Version of the format used in this manifest.

                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>

        </xs:complexType>

    </xs:element>

</xs:schema>