<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema' >

    <xs:include schemaLocation = 'Package/FreeCAD-Minimum.xsd' />
    <xs:include schemaLocation = 'Package/FreeCAD-Maximum.xsd' />
    <xs:include schemaLocation = 'Package/Python-Minimum.xsd' />
    <xs:include schemaLocation = 'Package/Description.xsd' />
    <xs:include schemaLocation = 'Package/Maintainer.xsd' />
    <xs:include schemaLocation = 'Package/Conflict.xsd' />
    <xs:include schemaLocation = 'Package/License.xsd' />
    <xs:include schemaLocation = 'Package/Version.xsd' />
    <xs:include schemaLocation = 'Package/Replace.xsd' />
    <xs:include schemaLocation = 'Package/Content.xsd' />
    <xs:include schemaLocation = 'Package/Depend.xsd' />
    <xs:include schemaLocation = 'Package/Author.xsd' />
    <xs:include schemaLocation = 'Package/Name.xsd' />
    <xs:include schemaLocation = 'Package/Date.xsd' />
    <xs:include schemaLocation = 'Package/Url.xsd' />
    <xs:include schemaLocation = 'Package/Tag.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:element name = 'package' >

        <xs:annotation>
            <xs:documentation xml:lang = 'en' >

                [🛈](https://wiki.freecad.org/Package_Metadata#.3Cpackage.3E)

                Declares an addon.

            </xs:documentation>
        </xs:annotation>

        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

        <xs:complexType>

            <xs:sequence>
                <xs:choice maxOccurs = 'unbounded' >

                    <xs:element ref = 'description' />
                    <xs:element ref = 'content' />
                    <xs:element ref = 'license' />
                    <xs:element ref = 'version' />
                    <xs:element ref = 'date' />
                    <xs:element ref = 'name' />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'maintainer'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'url'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'depend'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'conflict'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'replace'
                    />

                    <xs:element
                        maxOccurs = 'unbounded'
                        ref = 'tag'
                    />

                    <xs:element ref = 'freecadmin' />
                    <xs:element ref = 'freecadmax' />
                    <xs:element ref = 'pythonmin' />

                </xs:choice>
            </xs:sequence>

            <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

            <xs:attribute
                type = 'Manifest-Version'
                name = 'format'
                use = 'required'
            >

                <xs:annotation>
                    <xs:documentation>

                        [🛈](https://wiki.freecad.org/Package_Metadata#Attributes)

                        Version of the format used in this manifest.

                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>

        </xs:complexType>

    </xs:element>

</xs:schema>