<?xml
    version = '1.1'
    encoding = 'UTF-8'
?>

<xs:schema
    xmlns:xs = 'http://www.w3.org/2001/XMLSchema'
>

    <xs:include schemaLocation = 'License.xsd' />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Manifest-Version' >

        <xs:restriction base = 'xs:integer'>
            <xs:enumeration value = '1' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Version' >

        <xs:union memberTypes = 'Semantic-Version Calender-Version' />

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Semantic-Version' >

        <xs:restriction base = 'xs:token'>
            <xs:pattern value = '\d+(\.\d+){0,2}(-\w+)?' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Calender-Version' >

        <xs:restriction base = 'xs:token'>
            <xs:pattern value = '\d{2,4}\.\d{2}\.\d{2}(-\w+)?' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'Email' >

        <xs:restriction base = 'xs:string'>
            <xs:pattern value = '[^@]+@[^\.]+\..+' />
        </xs:restriction>

    </xs:simpleType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <xs:simpleType name = 'License' >

        <xs:union>

            <!-- Custom License -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:pattern value = '[\s\S]+' />
                </xs:restriction>
            </xs:simpleType>

            <!-- FreeCAD Specific -->

            <xs:simpleType>
                <xs:restriction base = 'xs:string' >
                    <xs:enumeration value = 'UNLICENSED' />
                </xs:restriction>
            </xs:simpleType>

            <!-- SPDX Licenses -->

             <xs:simpleType>
                <xs:restriction base = 'SPDX-License' />
            </xs:simpleType>

        </xs:union>

    </xs:simpleType>

</xs:schema>