
name : Bundle & Attach

on :
    release :
        types : [ created ]

jobs:
    build:

        runs-on : ubuntu-latest

        steps:

            -   name : Checkout repository
                uses : actions/checkout@v4

            -   name : Set up Python
                uses : actions/setup-python@v5
                with :
                    python-version : '3.x'
                    architecture : 'x64'

            -   name : Run bundle command
                run : python Scripts/Bundle.py

            -   name : Upload bundled schema
                uses : softprops/action-gh-release@v2
                with :
                    tag_name : ${{ github.event.release.tag_name }}
                    files : .build/Schema.xsd
